# Generated by Django 4.2.2 on 2023-06-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
